-- =============================================================
-- Mammoth Menu Learner — seed data
-- Supabase SQL Editor에 붙여넣어 실행 (최초 1회)
-- =============================================================

-- actions.default_duration: integer → text 타입 변경
ALTER TABLE actions ALTER COLUMN default_duration TYPE text;

-- 1. menu_categories
INSERT INTO menu_categories (name) VALUES ('커피') ON CONFLICT (name) DO NOTHING;
INSERT INTO menu_categories (name) VALUES ('논커피') ON CONFLICT (name) DO NOTHING;
INSERT INTO menu_categories (name) VALUES ('콜드브루') ON CONFLICT (name) DO NOTHING;
INSERT INTO menu_categories (name) VALUES ('티/에이드') ON CONFLICT (name) DO NOTHING;
INSERT INTO menu_categories (name) VALUES ('프라페/블렌디드') ON CONFLICT (name) DO NOTHING;

-- 2. ingredients
INSERT INTO ingredients (name, category) VALUES ('냉수', '기본') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('온수', '기본') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('얼음', '기본') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('코코넛 워터', '특수') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('에스프레소 샷', '커피') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('디카페인 샷', '커피') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('콜드브루', '커피') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('우유', '우유') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('저지방 우유', '우유') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('아몬드 브리즈', '우유') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('오트사이드', '우유') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('두유', '우유') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('시그니처 우유', '특수') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('코코넛 밀크', '특수') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('제로콜라', '특수') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('레드불', '특수') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('설탕 시럽', '시럽') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('아몬드 시럽', '시럽') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('바닐라 시럽', '시럽') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('블루베리 시럽', '시럽') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('패션후르츠 시럽', '시럽') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('사이다', '기본') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('페퍼민트', '허브티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('캐모마일', '허브티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('얼그레이', '티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('머스캣 그린', '티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('오렌지 루이보스', '허브티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('애플 히비스커스', '허브티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('레몬&오렌지 홍차', '티') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('건조사과칩', '토핑') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name, category) VALUES ('초코 파우더', '토핑') ON CONFLICT (name) DO NOTHING;

-- 3. actions
INSERT INTO actions (name, default_duration) VALUES ('젓기', '2~3회') ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('블렌더', '레벨3') ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('우유 스팀', '65도') ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('저울 계량', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('우리기', '2분') ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('칠링', '얼음 8알 정도') ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('평 리드', NULL) ON CONFLICT (name) DO NOTHING;
INSERT INTO actions (name, default_duration) VALUES ('돔 리드', NULL) ON CONFLICT (name) DO NOTHING;

-- 4. menus
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('아메리카노', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('샷추가 아메리카노', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('꿀커피', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('카페 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('꿀 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('바닐라 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('아몬드 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('시그니처 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '신메뉴', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('골든 코코넛 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('카페 모카', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('헤이즐넛 커피', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('헤이즐넛 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('헤이즐넛 모카', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('베트남 연유 커피', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('바나나 달달 커피', (SELECT id FROM menu_categories WHERE name='커피'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('아샷추 복숭아 아이스티', (SELECT id FROM menu_categories WHERE name='커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('솔티드 카라멜 마키아토', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('아인슈페너 커피', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('아인슈페너 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('바닐라 크럼블 아이스크림 라떼', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('믹스 커피', (SELECT id FROM menu_categories WHERE name='커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('샷추가 파인애플 주스', (SELECT id FROM menu_categories WHERE name='커피'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('콜드브루', (SELECT id FROM menu_categories WHERE name='콜드브루'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('콜드브루 라떼', (SELECT id FROM menu_categories WHERE name='콜드브루'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('돌체 콜드브루 라떼', (SELECT id FROM menu_categories WHERE name='콜드브루'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('달고나 콜드브루 라떼', (SELECT id FROM menu_categories WHERE name='콜드브루'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('레몬 토닉 콜드브루', (SELECT id FROM menu_categories WHERE name='콜드브루'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('딸기 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('초코 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('토피넛 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('고구마 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('곡물 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('달고나 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('스팀 밀크', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('로얄 밀크티', (SELECT id FROM menu_categories WHERE name='논커피'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('말차 클래식 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('말차 딸기 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('말차 클라우드 블루 코코넛 라떼', (SELECT id FROM menu_categories WHERE name='논커피'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('말차 클라우드 블루 코코넛 워터', (SELECT id FROM menu_categories WHERE name='티/에이드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('쌍화차', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('나주 배숙차', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('애플 모과차', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('포도 주스', (SELECT id FROM menu_categories WHERE name='티/에이드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('토마토 주스', (SELECT id FROM menu_categories WHERE name='티/에이드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('복숭아 아이스티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('매머드 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('인크레드불', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('유자 티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('유자 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('레몬밤 민트티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('청포도 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('깔라만시 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('장수 오미자티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('장수 오미자 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('한라봉티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('한라봉 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('청귤티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('청귤 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('자몽티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('자몽 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('블루레몬티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('블루레몬 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('히비스커스 유자티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('지리산 청매실티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('자몽 허니 블랙티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('오렌지 루이보스티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('애플 히비스커스티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('머스캣 그린티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('수박 주스', (SELECT id FROM menu_categories WHERE name='티/에이드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('파인애플 주스', (SELECT id FROM menu_categories WHERE name='티/에이드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('제로 복숭아 아이스티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', true);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('제로 체리콕 에이드', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('페퍼민트티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('캐모마일티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('얼그레이티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('레몬&오렌지(홍차)티', (SELECT id FROM menu_categories WHERE name='티/에이드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('말차 제주 레몬 크러쉬', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('말차 클래식 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '신메뉴', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('초코 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('민트 초코 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('피스타치오 아몬드 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('자바칩 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('바나나 초코칩 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('딸기 쿠키 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('콜드브루 커피 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('오레오 초코 프라페', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('플레인 요거트 스무디', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('딸기 요거트 스무디', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('블루베리 요거트 스무디', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('리얼 배 스무디', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('리얼 복숭아 스무디', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('리얼 망고 스무디', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('포도 사과젤리 크러쉬', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '단종예정', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('밀크쉐이크', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('딸기 밀크쉐이크', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('피넛버터 밀크쉐이크', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', false);
INSERT INTO menus (name, category_id, status, is_popular) VALUES ('곡물 쉐이크', (SELECT id FROM menu_categories WHERE name='프라페/블렌디드'), '상시', true);

-- 5. base_recipes
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='아메리카노'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='샷추가 아메리카노'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='꿀커피'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='카페 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='꿀 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='바닐라 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='아몬드 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='시그니처 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='골든 코코넛 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='카페 모카'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='헤이즐넛 커피'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='헤이즐넛 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='헤이즐넛 모카'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='베트남 연유 커피'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='바나나 달달 커피'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='아샷추 복숭아 아이스티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='솔티드 카라멜 마키아토'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='아인슈페너 커피'), '아이스', 'S', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='아인슈페너 라떼'), '아이스', 'S', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='바닐라 크럼블 아이스크림 라떼'), '아이스', 'S', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='믹스 커피'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='샷추가 파인애플 주스'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='콜드브루'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='콜드브루 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='돌체 콜드브루 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='달고나 콜드브루 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='레몬 토닉 콜드브루'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='딸기 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='초코 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='토피넛 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='고구마 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='곡물 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='달고나 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='스팀 밀크'), '핫', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='로얄 밀크티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='말차 클래식 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='말차 딸기 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='말차 클라우드 블루 코코넛 라떼'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='말차 클라우드 블루 코코넛 워터'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='쌍화차'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='나주 배숙차'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='애플 모과차'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='포도 주스'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='토마토 주스'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='복숭아 아이스티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='매머드 에이드'), '아이스', 'L', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='인크레드불'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='유자 티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='유자 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='레몬밤 민트티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='청포도 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='깔라만시 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='장수 오미자티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='장수 오미자 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='한라봉티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='한라봉 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='청귤티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='청귤 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='자몽티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='자몽 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='블루레몬티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='블루레몬 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='히비스커스 유자티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='지리산 청매실티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='자몽 허니 블랙티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='오렌지 루이보스티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='애플 히비스커스티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='머스캣 그린티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='수박 주스'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='파인애플 주스'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='제로 복숭아 아이스티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='제로 체리콕 에이드'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='페퍼민트티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='캐모마일티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='얼그레이티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='레몬&오렌지(홍차)티'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='말차 제주 레몬 크러쉬'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='말차 클래식 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='초코 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='민트 초코 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='피스타치오 아몬드 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='자바칩 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='바나나 초코칩 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='딸기 쿠키 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='콜드브루 커피 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='오레오 초코 프라페'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='플레인 요거트 스무디'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='딸기 요거트 스무디'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='블루베리 요거트 스무디'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='리얼 배 스무디'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='리얼 복숭아 스무디'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='리얼 망고 스무디'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='포도 사과젤리 크러쉬'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='밀크쉐이크'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='딸기 밀크쉐이크'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='피넛버터 밀크쉐이크'), '아이스', 'M', '일회용컵', NULL);
INSERT INTO base_recipes (menu_id, default_temp, default_size, default_cup, note) VALUES ((SELECT id FROM menus WHERE name='곡물 쉐이크'), '아이스', 'M', '일회용컵', NULL);

-- 6. recipe_steps (현재 아메리카노 3건만 입력됨)
INSERT INTO recipe_steps (base_recipe_id, order_num, ingredient_id, action_id, amount) VALUES ((SELECT id FROM base_recipes WHERE menu_id=(SELECT id FROM menus WHERE name='아메리카노')), 1, (SELECT id FROM ingredients WHERE name='얼음'), NULL, NULL);
INSERT INTO recipe_steps (base_recipe_id, order_num, ingredient_id, action_id, amount) VALUES ((SELECT id FROM base_recipes WHERE menu_id=(SELECT id FROM menus WHERE name='아메리카노')), 2, (SELECT id FROM ingredients WHERE name='물'), NULL, NULL);
INSERT INTO recipe_steps (base_recipe_id, order_num, ingredient_id, action_id, amount) VALUES ((SELECT id FROM base_recipes WHERE menu_id=(SELECT id FROM menus WHERE name='아메리카노')), 3, (SELECT id FROM ingredients WHERE name='에스프레소 샷'), NULL, '2샷');

-- option_diffs: 추후 입력
-- 7. option_diffs
INSERT INTO option_diffs (menu_id, option_type, option_value, diff_steps, diff_note) VALUES ((SELECT id FROM menus WHERE name='아메리카노'), 'variant', '아이스_S', '["얼음", "냉수", {"item": "에스프레소 샷", "amount": "1샷"}]'::jsonb, NULL);
INSERT INTO option_diffs (menu_id, option_type, option_value, diff_steps, diff_note) VALUES ((SELECT id FROM menus WHERE name='아메리카노'), 'variant', '아이스_L', '["얼음", "냉수", {"item": "에스프레소 샷", "amount": "3샷"}]'::jsonb, NULL);
INSERT INTO option_diffs (menu_id, option_type, option_value, diff_steps, diff_note) VALUES ((SELECT id FROM menus WHERE name='아메리카노'), 'variant', '핫_S', '[{"item": "온수", "amount": "S"}, {"item": "에스프레소 샷", "amount": "1샷"}]'::jsonb, NULL);
INSERT INTO option_diffs (menu_id, option_type, option_value, diff_steps, diff_note) VALUES ((SELECT id FROM menus WHERE name='아메리카노'), 'variant', '핫_M', '[{"item": "온수", "amount": "M"}, {"item": "에스프레소 샷", "amount": "2샷"}]'::jsonb, NULL);
INSERT INTO option_diffs (menu_id, option_type, option_value, diff_steps, diff_note) VALUES ((SELECT id FROM menus WHERE name='아메리카노'), 'variant', '핫_L', '[{"item": "온수", "amount": "L"}, {"item": "에스프레소 샷", "amount": "3샷"}]'::jsonb, NULL);